openapi: 3.0.3
info:
  title: Task Management API
  description: API for managing tasks with Neon database backend
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of all tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '422':
          description: Validation error
  /tasks/{task_id}:
    put:
      summary: Update an existing task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
          description: ID of the task to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '404':
          description: Task not found
        '422':
          description: Validation error
    delete:
      summary: Delete a task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
          description: ID of the task to delete
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
components:
  schemas:
    TaskResponse:
      type: object
      required:
        - id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Optional task description
          nullable: true
        completed:
          type: boolean
          description: Completion status of the task
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last updated
    TaskCreateRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Optional task description
          nullable: true
    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 200
          nullable: true
        description:
          type: string
          description: Optional task description
          nullable: true
        completed:
          type: boolean
          description: Completion status of the task
          nullable: true